- hosts: webservers

  become: true

  tasks:

   - name: add apt key for nodesource

     become: true

     apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
     register: add_aptkey
     
   - name: debug add apt key for nodesource
     debug:
      - var: add_aptkey



   - name: add repo for nodesource
     become: true

     apt_repository:

                 repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'

                 update_cache: yes
     register: add_aptrepo            

   - name:  debug add repo for nodesource
     debug:
     - var: add_aptrepo     
                 

   - name: install nodejs

     become: true

     apt: name=nodejs
